version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=s6CrJ6b8QijbGGYl23EKrejgnUtA
      - MONGO_INITDB_DATABASE=gameDB
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://admin:s6CrJ6b8QijbGGYl23EKrejgnUtA@mongo:27017/gameDB?authSource=admin
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_SOCKET_IO_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: [ "npm", "run", "dev" ]
    depends_on:
      - backend
volumes:
  mongo-data:
